const AYAT_AL_KURSI = `اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ`;
const IKHLAS = `قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ`;
const FALAQ = `قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ`;
const NAS = `قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ`;

const DECKS = [
  {
    id: 'sabah',
    title: 'أذكار الصباح',
    subtitle: 'Morning Remembrance',
    label: 'صباح',
    timeStart: 4,
    timeEnd: 12,
    accent: '#e8c97a',
    dim: '#3d3010',
    cards: [
      {
        id: 's1',
        title: 'دعاء الصباح',
        arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ',
        translation: 'We have reached the morning and at this very time unto Allah belongs all sovereignty, and all praise is for Allah. None has the right to be worshipped but Allah, alone, without partner. His is the dominion and His is the praise, and He is able to do all things. O Lord, I ask You for the good of this day and the good of what follows it.',
        count: 1,
        source: 'مسلم ٢٧٢٣',
        benefit: 'دعاء يُستفتح به اليوم ليكون في كنف الله وحمايته من شرور اليوم وما بعده',
      },
      {
        id: 's2',
        title: 'دعاء الصباح والمساء',
        arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
        translation: 'O Allah, by You we enter the morning and by You we enter the evening. By You we live and by You we die, and to You is the Resurrection.',
        count: 1,
        source: 'الترمذي ٣٣٩١',
        benefit: 'إقرار بأن الحياة والموت والبعث كلها بيد الله وحده',
      },
      {
        id: 's3',
        title: 'آية الكرسي',
        arabic: AYAT_AL_KURSI,
        translation: 'Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.',
        count: 1,
        source: 'البقرة: ٢٥٥',
        benefit: 'من قرأها في الصباح حفظه الله حتى المساء. قال النبي ﷺ: "من قرأها دبر كل صلاة مكتوبة لم يمنعه من دخول الجنة إلا أن يموت"',
      },
      {
        id: 's4',
        title: 'سورة الإخلاص',
        arabic: IKHLAS,
        translation: 'Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. Nor is there to Him any equivalent.',
        count: 3,
        source: 'أبو داود ٥٠٨٢',
        benefit: 'قراءتها ثلاثاً تعدل ختم القرآن كاملاً. وهي حرز من كل شر وبلاء',
      },
      {
        id: 's5',
        title: 'سورة الفلق',
        arabic: FALAQ,
        translation: 'Say: I seek refuge in the Lord of daybreak. From the evil of what He has created. And from the evil of darkness when it settles. And from the evil of those who blow on knots. And from the evil of an envier when he envies.',
        count: 3,
        source: 'أبو داود ٥٠٨٢',
        benefit: 'حرز من العين والسحر وسائر الشرور. كان النبي ﷺ يتعوذ بهما من الجن والعين',
      },
      {
        id: 's6',
        title: 'سورة الناس',
        arabic: NAS,
        translation: 'Say: I seek refuge in the Lord of mankind. The Sovereign of mankind. The God of mankind. From the evil of the retreating whisperer. Who whispers in the breasts of mankind. From among the jinn and mankind.',
        count: 3,
        source: 'أبو داود ٥٠٨٢',
        benefit: 'حرز من وسوسة الشيطان ومن شر الجن والإنس',
      },
      {
        id: 's7',
        title: 'حرز الصباح',
        arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
        translation: 'In the name of Allah with whose name nothing can cause harm in the earth or in the heavens, and He is the All-Hearing, the All-Knowing.',
        count: 3,
        source: 'أبو داود ٥٠٨٨، الترمذي ٣٣٨٨',
        benefit: 'من قالها ثلاثاً في الصباح لم تصبه فجأة بلاء حتى يمسي، ومن قالها ثلاثاً في المساء لم تصبه فجأة بلاء حتى يصبح',
      },
      {
        id: 's8',
        title: 'الرضا بالله',
        arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا',
        translation: 'I am pleased with Allah as my Lord, Islam as my religion, and Muhammad (ﷺ) as my Prophet.',
        count: 3,
        source: 'أبو داود ٥٠٧٢، الترمذي ٣٣٨٩',
        benefit: 'من قالها حين يصبح وحين يمسي كان حقاً على الله أن يرضيه يوم القيامة',
      },
      {
        id: 's9',
        title: 'سيد الاستغفار',
        arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ لَكَ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
        translation: 'O Allah, You are my Lord, none has the right to be worshipped but You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek Your protection from the evil of what I have done. I acknowledge Your favors upon me, and I acknowledge my sins. So forgive me, for none forgives sins except You.',
        count: 1,
        source: 'البخاري ٦٣٠٦',
        benefit: 'من قاله موقناً في الصباح فمات من يومه دخل الجنة. وهو سيد الاستغفار وأفضل دعاء طلب المغفرة',
      },
      {
        id: 's10',
        title: 'التهليل',
        arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
        translation: 'None has the right to be worshipped but Allah alone, without partner. His is the dominion, His is all praise, and He is able to do all things.',
        count: 10,
        source: 'النسائي، عمل اليوم والليلة ٢٤',
        benefit: 'من قالها عشراً في الصباح كتب الله له عشر حسنات، ومحا عنه عشر سيئات، وكانت له عدل عشر رقاب، وحفظه الله حتى يمسي',
      },
      {
        id: 's11',
        title: 'تسبيح الصباح',
        arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ، وَرِضَا نَفْسِهِ، وَزِنَةَ عَرْشِهِ، وَمِدَادَ كَلِمَاتِهِ',
        translation: 'Glory be to Allah and all praise is His, by the number of His creation, by His pleasure, by the weight of His Throne, and by the extent of His words.',
        count: 3,
        source: 'مسلم ٢٧٢٦',
        benefit: 'هذه الصيغة أفضل صيغ الذكر لأنها مقيدة بما لا يُحصى من المخلوقات والكلمات',
      },
      {
        id: 's12',
        title: 'الإشهاد',
        arabic: 'اللَّهُمَّ إِنِّي أَصْبَحْتُ أُشْهِدُكَ، وَأُشْهِدُ حَمَلَةَ عَرْشِكَ، وَمَلَائِكَتَكَ، وَجَمِيعَ خَلْقِكَ، أَنَّكَ أَنْتَ اللَّهُ لَا إِلَهَ إِلَّا أَنْتَ وَحْدَكَ لَا شَرِيكَ لَكَ، وَأَنَّ مُحَمَّدًا عَبْدُكَ وَرَسُولُكَ',
        translation: 'O Allah, I witness, and call upon You to witness, along with the bearers of Your Throne, Your angels, and all of Your creation, that You are Allah, none has the right to be worshipped but You alone, without partner, and that Muhammad is Your servant and messenger.',
        count: 4,
        source: 'أبو داود ٥٠٧٢، البخاري في الأدب المفرد',
        benefit: 'من قالها أربعاً في الصباح أعتقه الله من النار ذلك اليوم',
      },
      {
        id: 's13',
        title: 'شكر النعمة',
        arabic: 'اللَّهُمَّ مَا أَصْبَحَ بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ، فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ',
        translation: 'O Allah, whatever blessing I or any of Your creation have received upon this morning is from You alone, without partner. To You belongs all praise and thanks.',
        count: 1,
        source: 'أبو داود ٥٠٧٣، النسائي',
        benefit: 'من قالها حين يصبح فقد أدّى شكر يومه',
      },
      {
        id: 's14',
        title: 'التوكل',
        arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
        translation: 'Allah is sufficient for me. None has the right to be worshipped but Him. In Him I put my trust and He is the Lord of the Mighty Throne.',
        count: 7,
        source: 'أبو داود ٥٠٨١',
        benefit: 'من قالها سبعاً حين يصبح وحين يمسي كفاه الله ما أهمه من أمر الدنيا والآخرة',
      },
      {
        id: 's15',
        title: 'دعاء العافية',
        arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَهَ إِلَّا أَنْتَ. اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، لَا إِلَهَ إِلَّا أَنْتَ',
        translation: 'O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight. None has the right to be worshipped but You. O Allah, I seek Your protection from disbelief and poverty, and I seek Your protection from the punishment of the grave. None has the right to be worshipped but You.',
        count: 3,
        source: 'أبو داود ٥٠٩٠، أحمد',
        benefit: 'سؤال الله العافية الشاملة في البدن والحواس والدين والدنيا والآخرة',
      },
    ]
  },
  {
    id: 'masaa',
    title: 'أذكار المساء',
    subtitle: 'Evening Remembrance',
    label: 'مساء',
    timeStart: 15,
    timeEnd: 23,
    accent: '#a98fd4',
    dim: '#200d3d',
    cards: [
      {
        id: 'm1',
        title: 'دعاء المساء',
        arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذِهِ اللَّيْلَةِ وَشَرِّ مَا بَعْدَهَا',
        translation: 'We have reached the evening and the whole kingdom belongs to Allah. All praise is for Allah. None has the right to be worshipped but Allah, alone, without partner. His is the dominion and His is all praise, and He is able to do all things. O Lord, I ask You for the good of this night and the good of what follows it.',
        count: 1,
        source: 'مسلم ٢٧٢٣',
        benefit: 'دعاء يُختتم به اليوم ليكون في كنف الله وحمايته من شرور الليل وما بعده',
      },
      {
        id: 'm2',
        title: 'دعاء المساء',
        arabic: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ',
        translation: 'O Allah, by You we enter the evening and by You we enter the morning. By You we live and by You we die, and to You is the return.',
        count: 1,
        source: 'الترمذي ٣٣٩١',
        benefit: 'إقرار بأن الحياة والموت والمصير كلها بيد الله وحده',
      },
      {
        id: 'm3',
        title: 'آية الكرسي',
        arabic: AYAT_AL_KURSI,
        translation: 'Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth.',
        count: 1,
        source: 'البقرة: ٢٥٥',
        benefit: 'من قرأها حين يمسي حفظه الله حتى يصبح. أعظم آية في القرآن الكريم',
      },
      {
        id: 'm4', title: 'سورة الإخلاص', arabic: IKHLAS,
        translation: 'Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. Nor is there to Him any equivalent.',
        count: 3, source: 'أبو داود ٥٠٨٢',
        benefit: 'قراءتها ثلاثاً مساءً تعدل ختم القرآن كاملاً وتكون حرزاً من كل شر طوال الليل',
      },
      {
        id: 'm5', title: 'سورة الفلق', arabic: FALAQ,
        translation: 'Say: I seek refuge in the Lord of daybreak from the evil of what He has created and from the evil of darkness when it settles.',
        count: 3, source: 'أبو داود ٥٠٨٢',
        benefit: 'حرز من العين والسحر وسائر الشرور طوال الليل',
      },
      {
        id: 'm6', title: 'سورة الناس', arabic: NAS,
        translation: 'Say: I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer.',
        count: 3, source: 'أبو داود ٥٠٨٢',
        benefit: 'حرز من وسوسة الشيطان ومن شر الجن والإنس',
      },
      {
        id: 'm7',
        title: 'حرز المساء',
        arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
        translation: 'In the name of Allah with whose name nothing can cause harm in the earth or in the heavens, and He is the All-Hearing, the All-Knowing.',
        count: 3,
        source: 'أبو داود ٥٠٨٨، الترمذي ٣٣٨٨',
        benefit: 'من قالها ثلاثاً في المساء لم تصبه فجأة بلاء حتى يصبح',
      },
      {
        id: 'm8',
        title: 'الرضا',
        arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا',
        translation: 'I am pleased with Allah as my Lord, Islam as my religion, and Muhammad (ﷺ) as my Prophet.',
        count: 3,
        source: 'الترمذي ٣٣٨٩',
        benefit: 'من قالها حين يمسي كان حقاً على الله أن يرضيه يوم القيامة',
      },
      {
        id: 'm9',
        title: 'سيد الاستغفار',
        arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ لَكَ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
        translation: 'O Allah, You are my Lord, none has the right to be worshipped but You. You created me and I am Your servant. I abide by Your covenant and promise as best I can. I seek Your protection from the evil of what I have done. I acknowledge Your favors upon me and I confess my sins. Forgive me, for none forgives sins except You.',
        count: 1,
        source: 'البخاري ٦٣٠٦',
        benefit: 'من قاله موقناً في المساء فمات من ليلته دخل الجنة. وهو سيد الاستغفار',
      },
      {
        id: 'm10',
        title: 'التهليل مساءً',
        arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
        translation: 'None has the right to be worshipped but Allah alone, without partner. His is the dominion, His is all praise, and He is able to do all things.',
        count: 10,
        source: 'النسائي، عمل اليوم والليلة',
        benefit: 'من قالها عشراً في المساء كتب الله له عشر حسنات، ومحا عنه عشر سيئات، وحفظه الله حتى يصبح',
      },
      {
        id: 'm11',
        title: 'تسبيح المساء',
        arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ، وَرِضَا نَفْسِهِ، وَزِنَةَ عَرْشِهِ، وَمِدَادَ كَلِمَاتِهِ',
        translation: 'Glory be to Allah and all praise is His, by the number of His creation, by His pleasure, by the weight of His Throne, and by the extent of His words.',
        count: 3,
        source: 'مسلم ٢٧٢٦',
        benefit: 'هذه الصيغة أفضل صيغ التسبيح وأعظمها ثواباً',
      },
      {
        id: 'm12',
        title: 'التوكل مساءً',
        arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
        translation: 'Allah is sufficient for me. None has the right to be worshipped but Him. In Him I put my trust and He is the Lord of the Mighty Throne.',
        count: 7,
        source: 'أبو داود ٥٠٨١',
        benefit: 'من قالها سبعاً حين يمسي كفاه الله ما أهمه من أمر الدنيا والآخرة',
      },
    ]
  },
  {
    id: 'salah',
    title: 'أذكار بعد الصلاة',
    subtitle: 'After Prayer',
    label: 'صلاة',
    accent: '#7ac4a0',
    dim: '#0a2a1c',
    cards: [
      {
        id: 'p1',
        title: 'الاستغفار',
        arabic: 'أَسْتَغْفِرُ اللَّهَ',
        translation: 'I seek forgiveness from Allah.',
        count: 3,
        source: 'مسلم ٥٩١',
        benefit: 'يُقال ثلاثاً عقب كل صلاة. قال النبي ﷺ: "وَاللَّهِ إِنِّي لَأَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ فِي الْيَوْمِ أَكْثَرَ مِنْ سَبْعِينَ مَرَّةً"',
      },
      {
        id: 'p2',
        title: 'دعاء السلام',
        arabic: 'اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ',
        translation: 'O Allah, You are Peace and from You comes peace. Blessed are You, O Possessor of majesty and honor.',
        count: 1,
        source: 'مسلم ٥٩١',
        benefit: 'يُقال دبر كل صلاة مكتوبة عقب الاستغفار. فيه إقرار بأن السلام والأمان من الله وحده',
      },
      {
        id: 'p3',
        title: 'لا إله إلا الله',
        arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
        translation: 'None has the right to be worshipped but Allah alone, without partner. His is the dominion and His is all praise, and He is able to do all things.',
        count: 1,
        source: 'مسلم ٥٩٧',
        benefit: 'من قالها دبر كل صلاة غُفرت له ذنوبه وإن كانت مثل زبد البحر',
      },
      {
        id: 'p4',
        title: 'لا حول ولا قوة',
        arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
        translation: 'There is no power nor might except with Allah.',
        count: 1,
        source: 'البخاري ٦٣٨٤',
        benefit: 'كنز من كنوز الجنة. من قالها دبر كل صلاة فُتحت له أبواب الجنة الثمانية',
      },
      {
        id: 'p5',
        title: 'سبحان الله',
        arabic: 'سُبْحَانَ اللَّهِ',
        translation: 'Glory be to Allah.',
        count: 33,
        source: 'مسلم ٥٩٥',
        benefit: 'من سبّح دبر كل صلاة ثلاثاً وثلاثين، وحمد ثلاثاً وثلاثين، وكبّر ثلاثاً وثلاثين، وقال لا إله إلا الله وحده... غُفرت خطاياه وإن كانت مثل زبد البحر',
      },
      {
        id: 'p6',
        title: 'الحمد لله',
        arabic: 'الْحَمْدُ لِلَّهِ',
        translation: 'All praise is for Allah.',
        count: 33,
        source: 'مسلم ٥٩٥',
        benefit: 'الحمد لله كلمة تملأ الميزان يوم القيامة',
      },
      {
        id: 'p7',
        title: 'الله أكبر',
        arabic: 'اللَّهُ أَكْبَرُ',
        translation: 'Allah is the Greatest.',
        count: 33,
        source: 'مسلم ٥٩٥',
        benefit: 'أعظم الكلمات وأحبها إلى الله. يُكمل بها المئة فيقال: لا إله إلا الله وحده لا شريك له...',
      },
      {
        id: 'p8',
        title: 'ختم التسبيح',
        arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
        translation: 'None has the right to be worshipped but Allah alone, without partner. His is the dominion and His is all praise, and He is able to do all things.',
        count: 1,
        source: 'مسلم ٥٩٧',
        benefit: 'تُقال مرة واحدة بعد إكمال التسبيح والتحميد والتكبير لتكتمل المئة',
      },
      {
        id: 'p9',
        title: 'آية الكرسي',
        arabic: AYAT_AL_KURSI,
        translation: 'Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep.',
        count: 1,
        source: 'النسائي، عمل اليوم والليلة',
        benefit: 'من قرأها دبر كل صلاة مكتوبة لم يمنعه من دخول الجنة إلا أن يموت',
      },
    ]
  },
  {
    id: 'nawm',
    title: 'أذكار النوم',
    subtitle: 'Before Sleep',
    label: 'نوم',
    timeStart: 21,
    timeEnd: 4,
    accent: '#7a9fd4',
    dim: '#0a1530',
    cards: [
      {
        id: 'n1',
        title: 'دعاء النوم',
        arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
        translation: 'In Your name, O Allah, I die and I live.',
        count: 1,
        source: 'البخاري ٦٣٢٤',
        benefit: 'يُقال عند النوم. النوم موت صغير والاستيقاظ حياة جديدة. فيه توحيد وتوكل على الله',
      },
      {
        id: 'n2',
        title: 'آية الكرسي',
        arabic: AYAT_AL_KURSI,
        translation: 'Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep.',
        count: 1,
        source: 'البخاري ٢٣١١',
        benefit: 'قال النبي ﷺ لمن يقرأها قبل النوم: "لن يزال عليك من الله حافظ ولا يقربك شيطان حتى تصبح"',
      },
      {
        id: 'n3', title: 'سورة الإخلاص', arabic: IKHLAS,
        translation: 'Say: He is Allah, the One. Allah, the Eternal Refuge.',
        count: 3, source: 'أبو داود، الترمذي',
        benefit: 'كان النبي ﷺ إذا أوى إلى فراشه جمع كفيه ونفث فيهن وقرأ المعوذات فمسح بهما جسده',
      },
      {
        id: 'n4', title: 'سورة الفلق', arabic: FALAQ,
        translation: 'Say: I seek refuge in the Lord of daybreak from the evil of what He has created.',
        count: 3, source: 'الترمذي ٣٤٠٢',
        benefit: 'حرز من كل شر وعين وسحر أثناء النوم',
      },
      {
        id: 'n5', title: 'سورة الناس', arabic: NAS,
        translation: 'Say: I seek refuge in the Lord of mankind, the Sovereign of mankind.',
        count: 3, source: 'الترمذي ٣٤٠٢',
        benefit: 'حرز من وسوسة الشيطان أثناء النوم والأحلام',
      },
      {
        id: 'n6',
        title: 'تسبيح فاطمة',
        arabic: 'سُبْحَانَ اللَّهِ',
        translation: 'Glory be to Allah.',
        count: 33,
        source: 'البخاري ٣١١٣',
        benefit: 'علّمه النبي ﷺ لفاطمة وعلي رضي الله عنهما بدلاً من الخادم. قال ﷺ: "هو خير لكما من خادم"',
      },
      {
        id: 'n7',
        title: 'تحميد النوم',
        arabic: 'الْحَمْدُ لِلَّهِ',
        translation: 'All praise is for Allah.',
        count: 33,
        source: 'البخاري ٣١١٣',
        benefit: 'من تسبيح فاطمة رضي الله عنها. يُقال قبل النوم ثلاثاً وثلاثين مرة',
      },
      {
        id: 'n8',
        title: 'تكبير النوم',
        arabic: 'اللَّهُ أَكْبَرُ',
        translation: 'Allah is the Greatest.',
        count: 34,
        source: 'البخاري ٣١١٣',
        benefit: 'آخر تسبيح فاطمة رضي الله عنها. أربعة وثلاثون تكبيرة قبل النوم',
      },
      {
        id: 'n9',
        title: 'دعاء المبيت',
        arabic: 'اللَّهُمَّ إِنَّكَ خَلَقْتَ نَفْسِي وَأَنْتَ تَوَفَّاهَا، لَكَ مَمَاتُهَا وَمَحْيَاهَا، إِنْ أَحْيَيْتَهَا فَاحْفَظْهَا، وَإِنْ أَمَتَّهَا فَاغْفِرْ لَهَا',
        translation: 'O Allah, You created my soul and You take it back. Its death and life belong to You. If You give it life then protect it, and if You cause it to die then forgive it.',
        count: 1,
        source: 'مسلم ٢٧١٢',
        benefit: 'فيه إقرار بأن الحياة والموت بيد الله وحده، وطلب الحفظ إن أحيا والمغفرة إن أمات',
      },
      {
        id: 'n10',
        title: 'دعاء العذاب',
        arabic: 'اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ',
        translation: 'O Allah, protect me from Your punishment on the Day You resurrect Your servants.',
        count: 3,
        source: 'أبو داود ٥٠٤٥، الترمذي',
        benefit: 'يُقال ثلاثاً عند الأوي إلى الفراش. سؤال الله السلامة من عذاب يوم القيامة',
      },
    ]
  }
];

// Export to window for global access
window.DECKS = DECKS;
